# Generated by Django 5.2 on 2025-05-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('User', 'User')], default='Admin', max_length=30, null=True, verbose_name='user_type'),
        ),
    ]
