# Generated by Django 5.2 on 2025-05-24 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_skills'),
        ('user_details', '0010_user_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='master_data.skills'),
        ),
    ]
