# Generated by Django 5.2 on 2025-05-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_skills'),
        ('user_details', '0011_user_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_skills', to='master_data.skills'),
        ),
    ]
