# Generated by Django 5.2 on 2025-05-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0012_remove_user_skills_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
