# Generated by Django 5.2 on 2025-06-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0013_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
