# Generated by Django 5.2 on 2025-07-02 03:21

import django.core.validators
import user_details.models
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0015_user_sub_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.FileField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=user_details.models.generate_banner_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity], verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=user_details.models.generate_profile_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity], verbose_name='screen Image'),
        ),
    ]
