# Generated by Django 5.2 on 2025-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0016_alter_banner_banner_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpstorage',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Mobile Number'),
        ),
    ]
