# Generated by Django 5.2 on 2025-07-13 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0019_user_aadhaar_number_user_blood_group_user_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='production_house',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recruit_slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_department',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('User', 'user'), ('Admin', 'admin')], default='user', max_length=30, null=True, verbose_name='user_type'),
        ),
    ]
