# Generated by Django 5.2 on 2025-07-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_rename_name_doctor_full_name'),
        ('user_details', '0021_user_full_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokens',
            name='doctor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
