# Generated by Django 5.2 on 2025-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0022_usertokens_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'indexes': [models.Index(fields=['full_name'], name='user_detail_full_na_6f7e0e_idx'), models.Index(fields=['phone'], name='user_detail_phone_69b80c_idx'), models.Index(fields=['email'], name='user_detail_email_a06fc5_idx')],
            },
        ),
    ]
