# Generated by Django 5.2 on 2025-09-17 18:08

import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0024_user_age_user_alternate_number_user_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.FileField(blank=True, null=True, storage=utils.custom_storages.FileStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=''),
        ),
    ]
