# Generated by Django 5.2 on 2025-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0025_alter_banner_banner_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
