# Generated by Django 5.2 on 2025-09-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0026_user_membership_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_details.user',),
        ),
    ]
