# Generated by Django 5.2 on 2025-09-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0027_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_details.enquiry',),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
