# Generated by Django 5.2 on 2025-10-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0030_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('User', 'user'), ('Admin', 'admin'), ('Front_Desk', 'front_desk')], default='user', max_length=30, null=True, verbose_name='user_type'),
        ),
    ]
