# Generated by Django 5.2 on 2025-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_city_updated_by_department_updated_by_and_more'),
        ('user_details', '0031_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
        migrations.AddField(
            model_name='user',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='hospital.hospital'),
        ),
    ]
