# Generated by Django 5.2 on 2025-12-28 13:19

import django.db.models.deletion
import utils.custom_storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0032_remove_user_hospital_user_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('grandfather', 'Grand Father'), ('grandmother', 'Grand Mother')], max_length=20)),
                ('aadhaar_number', models.CharField(blank=True, max_length=24, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=24, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=24, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to='')),
                ('membership_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
