# Generated by Django 5.2 on 2026-01-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0033_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
