# Generated by Django 5.2 on 2026-04-15 08:30

import django.core.validators
import django.db.models.deletion
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0034_familymember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Agent', 'Agent'), ('Corporate Office', 'Corporate Office'), ('Hospital', 'Hospital')], max_length=32)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=455, null=True)),
                ('referral_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'indexes': [models.Index(fields=['category'], name='user_detail_categor_724b88_idx'), models.Index(fields=['mobile'], name='user_detail_mobile_cac6d9_idx'), models.Index(fields=['email'], name='user_detail_email_e9c97e_idx'), models.Index(fields=['referral_code'], name='user_detail_referra_b61eda_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='user_details.partner'),
        ),
    ]
