# Generated by Codex on 2026-04-28

import django.core.validators
import user_details.models
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0035_user_referral_code_alter_familymember_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='profile_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=utils.custom_storages.MediaStorage(),
                upload_to=user_details.models.generate_family_member_profile_path,
                validators=[
                    django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']),
                    utils.constants.validate_file_size,
                    utils.constants.validate_file_authenticity,
                ],
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=utils.custom_storages.MediaStorage(),
                upload_to=user_details.models.generate_profile_path,
                validators=[
                    django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']),
                    utils.constants.validate_file_size,
                    utils.constants.validate_file_authenticity,
                ],
            ),
        ),
    ]
