# Generated by Django 5.2 on 2026-05-03 16:37

import django.core.validators
import user_details.models
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0036_alter_profile_image_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=user_details.models.generate_partner_profile_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=user_details.models.generate_partner_profile_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
    ]
