# Generated by Django 5.2 on 2026-05-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0037_partner_profile_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPatient',
            fields=[
            ],
            options={
                'verbose_name': 'Membership Card',
                'verbose_name_plural': 'Membership Cards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_details.user',),
        ),
    ]
