# Generated by Django 5.2 on 2026-05-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0038_membershippatient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPatient',
        ),
    ]
