# Generated by Django 5.2 on 2025-04-19 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('field_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('text', 'Text')], max_length=50)),
                ('field_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Custom Filed',
                'verbose_name_plural': 'Custom Fileds',
                'indexes': [models.Index(fields=['entity_type'], name='meta_app_en_entity__476141_idx'), models.Index(fields=['field_type'], name='meta_app_en_field_t_4d9e1a_idx'), models.Index(fields=['field_name'], name='meta_app_en_field_n_8933cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_value', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_app.entityfield')),
            ],
            options={
                'indexes': [models.Index(fields=['entity'], name='meta_app_li_entity__3b36a8_idx'), models.Index(fields=['list_value'], name='meta_app_li_list_va_aecb0d_idx')],
            },
        ),
    ]
