# Generated by Django 5.2 on 2025-07-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.hospital'),
        ),
    ]
