# Generated by Django 5.2 on 2025-07-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialisation',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
