# Generated by Django 5.2 on 2025-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_department_image_specialisation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='description',
            new_name='hospital_name',
        ),
        migrations.RenameField(
            model_name='specialisation',
            old_name='description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/'),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='speciality/'),
        ),
    ]
