# Generated by Django 5.2 on 2025-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_rename_description_hospital_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='speciality/'),
        ),
    ]
