# Generated by Django 5.2 on 2025-05-18 19:37

import apps.production_house.models
import django.core.validators
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhouse',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.production_house.models.generate_ph_profile_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
    ]
