# Generated by Django 5.2 on 2025-05-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0005_merge_20250523_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhouse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='email',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
