# Generated by Django 5.2 on 2025-07-02 03:21

import apps.production_house.models
import django.core.validators
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0006_productionhouse_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionhouse',
            name='certificate',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.production_house.models.generate_ph_certificate_image_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.production_house.models.generate_ph_profile_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
    ]
