# Generated by Django 5.2 on 2025-09-17 18:08

import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0007_alter_productionhouse_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionhouse',
            name='certificate',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=''),
        ),
    ]
