# Generated by Django 5.2 on 2025-09-17 18:08

import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0002_alter_page_featured_image_alter_pagesection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=''),
        ),
    ]
