version: "3.9"

services:
  db:
    image: postgres:16
    container_name: vaidya-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vaidya
      POSTGRES_USER: vaidya_postgres
      POSTGRES_PASSWORD: Bandhu@Vaidya@2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
