# Generated by Django 5.2 on 2025-07-13 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_group_name', models.CharField(max_length=50, null=True)),
                ('group_slug_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ApprGroup',
                'verbose_name_plural': 'App Groups',
                'indexes': [models.Index(fields=['group_slug_name'], name='approles_ap_group_s_3671ea_idx'), models.Index(fields=['role_type'], name='approles_ap_role_ty_53e612_idx'), models.Index(fields=['is_active'], name='approles_ap_is_acti_663e9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MasterModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, null=True)),
                ('module_slug_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Module',
                'verbose_name_plural': 'Master Modules',
                'indexes': [models.Index(fields=['module_slug_name'], name='approles_ma_module__ecd559_idx'), models.Index(fields=['is_active'], name='approles_ma_is_acti_faf97c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50, null=True)),
                ('permission_slug_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastermodule', to='approles.mastermodules')),
            ],
            options={
                'verbose_name': 'App Permission',
                'verbose_name_plural': 'App Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user_group', to='approles.appgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
            },
        ),
        migrations.CreateModel(
            name='AppGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(blank=True, choices=[('Everything', 'Everything'), ('Owner_only', 'Owner_only'), ('No_Access', 'No_Access')], default='No_Access', max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_group', to='approles.appgroup')),
                ('app_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_permission', to='approles.appmodules')),
            ],
            options={
                'verbose_name': 'AppGroupPermission',
                'verbose_name_plural': 'AppGroupPermissions',
                'indexes': [models.Index(fields=['app_permission'], name='approles_ap_app_per_f9f0f4_idx'), models.Index(fields=['app_group'], name='approles_ap_app_gro_684f34_idx'), models.Index(fields=['access_level'], name='approles_ap_access__d86546_idx'), models.Index(fields=['is_active'], name='approles_ap_is_acti_dca8ff_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='appmodules',
            index=models.Index(fields=['master_module'], name='approles_ap_master__72bd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='appmodules',
            index=models.Index(fields=['permission_slug_name'], name='approles_ap_permiss_0a7187_idx'),
        ),
        migrations.AddIndex(
            model_name='appmodules',
            index=models.Index(fields=['is_active'], name='approles_ap_is_acti_b0e2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroup',
            index=models.Index(fields=['user', 'app_group'], name='approles_us_user_id_c1f350_idx'),
        ),
    ]
