# Generated by Django 5.2 on 2025-06-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_alter_hospital_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=300)),
                ('name', models.CharField(max_length=512, verbose_name='First Name')),
                ('designation', models.CharField(blank=True, max_length=500, null=True)),
                ('title_text', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=800, null=True)),
                ('educational_degrees', models.CharField(blank=True, max_length=2046, null=True)),
                ('photo', models.URLField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fellowship_membership', models.TextField(blank=True, null=True)),
                ('field_expertise', models.TextField(blank=True, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=2046, null=True)),
                ('awards_achievements', models.TextField(blank=True, null=True)),
                ('talks_publications', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('other_meta_tags', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(null=True)),
                ('allow_website', models.SmallIntegerField(blank=True, null=True)),
                ('is_online_appointment_enable', models.BooleanField(default=True)),
                ('is_logged_in', models.BooleanField(default=False, verbose_name='is_logged_in')),
                ('slug', models.SlugField(blank=True, max_length=512, null=True)),
                ('hv_consultation_charges', models.IntegerField(default=0, null=True)),
                ('vc_consultation_charges', models.IntegerField(default=0, null=True)),
                ('pr_consultation_charges', models.IntegerField(default=0, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary_consultation_doctor', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.hospital')),
                ('speciality', models.ManyToManyField(blank=True, related_name='doctor_specialisation', to='hospital.specialisation')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'permissions': (),
                'unique_together': {('code', 'hospital')},
            },
        ),
    ]
