# Generated by Django 5.2 on 2025-05-26 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSchema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_title', models.CharField(max_length=50, null=True)),
                ('slug_name', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, null=True)),
                ('sectionkey', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, choices=[('tab', 'tab'), ('dynamic', 'dynamic')], max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('default_tab', models.BooleanField(default=True, verbose_name='Store data to parent tables')),
                ('enable_always', models.BooleanField(default=True, verbose_name='Tab Available in all Levels')),
                ('enable_candidate_edit', models.BooleanField(default=True, verbose_name='Can Candidate can allow to fill?')),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterschema', to='configurations.masterschema')),
            ],
            options={
                'verbose_name': 'Section Module',
                'verbose_name_plural': 'Section Modules',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='SectionFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('type', models.CharField(choices=[('text', 'text'), ('email', 'email'), ('number', 'number'), ('textarea', 'textarea'), ('dropdown', 'dropdown'), ('multiple-dropdown', 'multiple-dropdown'), ('checkbox', 'checkbox'), ('document', 'document'), ('phone', 'phone'), ('date', 'date'), ('time', 'time'), ('depedent_dropdown', 'depedent_dropdown'), ('hyperlink', 'hyperlink'), ('download_link', 'download_link'), ('p', 'p'), ('file', 'file')], default='text', max_length=150)),
                ('options', models.JSONField(blank=True, null=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=650, null=True)),
                ('ordering_number', models.IntegerField(blank=True, null=True)),
                ('linked_model_path', models.CharField(blank=True, max_length=250, null=True)),
                ('custom_options', models.JSONField(blank=True, null=True)),
                ('dependent_dropdown_slug', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_custom_field', models.BooleanField(default=False)),
                ('is_verification_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='configurations.sectionmodules')),
            ],
            options={
                'verbose_name': 'Tab Field',
                'verbose_name_plural': 'Tab Fields',
                'ordering': ['ordering_number'],
            },
        ),
        migrations.CreateModel(
            name='UserDynamicFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_values', to='configurations.sectionfields')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='sectionmodules',
            index=models.Index(fields=['section', 'type'], name='configurati_section_794355_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionmodules',
            index=models.Index(fields=['sectionkey'], name='configurati_section_ec4fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionmodules',
            index=models.Index(fields=['is_active'], name='configurati_is_acti_2228c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionfields',
            index=models.Index(fields=['section', 'type'], name='configurati_section_6aae09_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionfields',
            index=models.Index(fields=['name'], name='configurati_name_57a533_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionfields',
            index=models.Index(fields=['is_active'], name='configurati_is_acti_616387_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdynamicfieldvalue',
            unique_together={('user', 'field')},
        ),
    ]
