# Generated by Django 5.2 on 2025-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='budget',
            new_name='total_budget',
        ),
    ]
