# Generated by Django 5.2 on 2025-05-07 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_shootingrole'),
        ('movies', '0003_actoraudition_actoraward_actorpayment_actorportfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actorpayment',
            old_name='payment_method',
            new_name='accepted_payment_modes',
        ),
        migrations.RemoveField(
            model_name='actorpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='actorpayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='actorpayment',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='actorpayment',
            name='status',
        ),
        migrations.AddField(
            model_name='actorpayment',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actorpayment',
            name='interested_in_internship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actorpayment',
            name='shooting_roles',
            field=models.ManyToManyField(blank=True, related_name='actor_payments', to='master_data.shootingrole'),
        ),
        migrations.CreateModel(
            name='PaymentTypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Day', 'Day-wise'), ('Month', 'Month-wise'), ('Movie', 'Movie-wise'), ('Act', 'Act-wise')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actor_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_rates', to='movies.actorpayment')),
            ],
        ),
    ]
