# Generated by Django 5.2 on 2025-06-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttyperate',
            name='payment_type',
        ),
    ]
