# Generated by Django 5.2 on 2025-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_paymenttyperate_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actorpayment',
            old_name='accepted_payment_modes',
            new_name='upi_id',
        ),
        migrations.RenameField(
            model_name='paymenttyperate',
            old_name='rate',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='paymenttyperate',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttyperate',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
