# Generated by Django 5.2 on 2025-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_actorpayment_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttyperate',
            name='convenience_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
