# Generated by Django 5.2 on 2025-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
