# Generated by Django 5.2 on 2025-06-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_pricingmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='price_master',
            field=models.ManyToManyField(related_name='sub_department_price_master', to='master_data.pricingmaster'),
        ),
    ]
