# Generated by Django 5.2 on 2025-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_subdepartment_price_master'),
        ('payments', '0003_subscription_transaction_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='subscription_master',
            field=models.ManyToManyField(related_name='sub_department_subscription_master', to='payments.subscription'),
        ),
    ]
