# Generated by Django 5.2 on 2025-06-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_accounttype_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('key', models.SlugField(help_text='Internal use for form binding or APIs', max_length=255, unique=True)),
                ('input_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('radio', 'Radio'), ('select', 'Select'), ('date', 'Date'), ('boolean', 'Boolean')], default='number', max_length=20)),
                ('unit', models.CharField(choices=[('Rs', 'Rupees'), ('count', 'Count'), ('string', 'String'), ('%', 'Percentage'), ('', 'None')], default='Rs', max_length=20)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing Master',
                'verbose_name_plural': 'Pricing Masterdata',
                'ordering': ['title'],
            },
        ),
    ]
