# Generated by Django 5.2 on 2025-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_remove_subdepartment_subscription_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingmaster',
            name='input_type',
            field=models.JSONField(default={}),
        ),
    ]
