# Generated by Django 5.2 on 2025-09-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_alter_pricingmaster_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingmaster',
            name='input_type',
            field=models.JSONField(default=dict),
        ),
    ]
