# Generated by Django 5.2 on 2025-04-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('box_office_collection', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('production_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='production_house.productionhouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
