# Generated by Django 5.2 on 2025-05-17 17:03

import apps.movies.models
import django.core.validators
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_payment_method_actorpayment_accepted_payment_modes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorportfolio',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.movies.models.generate_profile_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
    ]
