# Generated by Django 5.2 on 2025-06-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_subdepartment_subscription_master'),
        ('movies', '0008_remove_paymenttyperate_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttyperate',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='master_data.pricingmaster'),
        ),
    ]
