# Generated by Django 5.2 on 2025-06-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_rename_accepted_payment_modes_actorpayment_upi_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorpayment',
            name='upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
