# Generated by Django 5.2 on 2025-07-02 03:21

import apps.movies.models
import django.core.validators
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_paymenttyperate_convenience_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorportfolio',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.movies.models.generate_profile_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cower_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.movies.models.generate_movie_images_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='display_picture',
            field=models.ImageField(storage=utils.custom_storages.MediaStorage(), upload_to=apps.movies.models.generate_movie_images_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
    ]
