# Generated by Django 5.2 on 2025-07-02 03:21

import apps.blog.models
import django.core.validators
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.blog.models.generate_blog_image_path, validators=[django.core.validators.FileExtensionValidator([]), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
    ]
