# Generated by Django 5.2 on 2025-06-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_remove_subdepartment_subscription_master'),
        ('payments', '0003_subscription_transaction_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_department',
            field=models.ManyToManyField(related_name='subscription_subscription_master', to='master_data.subdepartment'),
        ),
    ]
