# Generated by Django 5.2 on 2025-09-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
