# Generated by Django 5.2 on 2025-09-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_usersubscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='sub_department',
        ),
    ]
