# Generated by Django 5.2 on 2025-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile Number')),
                ('email_id', models.EmailField(blank=True, max_length=455, null=True)),
                ('otp_code', models.CharField(max_length=4)),
                ('otp_expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='OTP Key Expiration DateTime')),
                ('attempt', models.IntegerField()),
                ('is_existing_user', models.BooleanField(default=True, verbose_name='Is Verified Student')),
                ('is_verified', models.BooleanField(default=False, verbose_name='mobile Verified')),
                ('resend_count', models.IntegerField()),
                ('is_active', models.BooleanField(default=False, verbose_name='mobile Verified')),
            ],
            options={
                'verbose_name': 'OTP Storage',
                'verbose_name_plural': 'OTP Storages',
                'permissions': (),
            },
        ),
    ]
