# Generated by Django 5.2 on 2025-09-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(blank=True, max_length=455, null=True)),
                ('email', models.EmailField(blank=True, max_length=455, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
