# Generated by Django 5.2 on 2025-06-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, null=True, verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='0,0', null=True)),
                ('location_name', models.CharField(blank=True, max_length=512, null=True)),
                ('is_home_collection_supported', models.BooleanField(default=False)),
                ('is_health_package_online_purchase_supported', models.BooleanField(default=False)),
                ('health_package_doctor_code', models.CharField(blank=True, max_length=10, null=True)),
                ('health_package_department_code', models.CharField(blank=True, max_length=10, null=True)),
                ('corporate_only', models.BooleanField(default=False)),
                ('hospital_enabled', models.BooleanField(default=True)),
                ('promo_code', models.CharField(blank=True, max_length=30, null=True)),
                ('slot_blocking_duration', models.IntegerField(default=0)),
                ('allow_refund_on_cancellation', models.BooleanField(default=True)),
                ('hcu_support', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_email_id', models.TextField(blank=True, null=True)),
                ('unit_cc_email_id', models.TextField(blank=True, null=True)),
                ('doctor_sync_allowed', models.BooleanField(default=True)),
                ('health_package_sync_allowed', models.BooleanField(default=True)),
                ('lead_square_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_trakCare_enabled', models.BooleanField(default=False)),
                ('is_ca_unit', models.BooleanField(default=False)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_id', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vaccination_package_doctor_code', models.CharField(blank=True, max_length=15, null=True)),
                ('vaccination_package_department_code', models.CharField(blank=True, max_length=15, null=True)),
                ('vaccination_sync_allowed', models.BooleanField(default=False)),
                ('hpp_doctor_code', models.CharField(blank=True, max_length=15, null=True)),
                ('hpp_department_code', models.CharField(blank=True, max_length=15, null=True)),
                ('hpp_sync_allowed', models.BooleanField(default=False)),
                ('is_hpp_online_purchase_supported', models.BooleanField(default=False)),
                ('pc_location_code', models.CharField(blank=True, max_length=15, null=True)),
                ('pc_department_code', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.city')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.hospital')),
            ],
            options={
                'verbose_name': 'Specialisation',
                'verbose_name_plural': 'Specialisations',
            },
        ),
    ]
