"""
Django settings for KALAKSHETRA project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import ast
import datetime
import json
import os
from pathlib import Path
import environ
from boto3 import session as boto3_session
from botocore.client import Config as BotoConfig

# from .loggers import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables
env = environ.Env(
    # DEBUG=(bool, False),
    # SECRET_KEY=(str, "django-insecure-1^l_%acdj@6es-cjp#i()q2t*1sj(j2d!=c-mhl5o-vgg90fpq"),
    # ALLOWED_HOSTS=(list, ['*']),
    # AWS_STORAGE_BUCKET_NAME=(str, ''),
    # AWS_S3_REGION_NAME=(str, 'ap-south-1'),
    # USE_S3=(bool, False),
    # DOMAIN_NAME=(str, ''),
    # SITE_URL=(str, ''),
)

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = [
    # 'localhost',
    # '127.0.0.1',
    # '::1',
    # '.ngrok-free.app',
    '*'
]
USE_X_FORWARDED_HOST = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://stage.vaidyabandhu.com",
    "https://www.vaidyabandhu.com",
    "https://admin.vaidyabandhu.com",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://stage.vaidyabandhu.com",
    "https://admin.vaidyabandhu.com",
    "https://www.vaidyabandhu.com",
]

# Read .env.development file if it exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env.development'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1^l_%acdj@6es-cjp#i()q2t*1sj(j2d!=c-mhl5o-vgg90fpq"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = env('DEBUG')
DEBUG = True

# ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Application definition
PREDEFINED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
]

CORE_APPS = [
    "user_details",
    "apps.users",
    "apps.meta_app",
    "axes",
    "apps.master_data",
    "apps.production_house",
    "apps.movies",
    "apps.budget",
    "apps.event",
    "apps.blogs",
    "ckeditor",
    "apps.blog",
    "apps.web_pages",
    "apps.staticpages",
    "apps.configurations",
    "storages",
    "apps.payments",
    "apps.schedule",
    "apps.hospital",
    "apps.doctors",
    "apps.diagnostic",
    "apps.approles",
    "apps.slots",
]

INSTALLED_APPS = PREDEFINED_APPS + CORE_APPS

JAZZMIN_SETTINGS = {
    "site_title": "Vaidya Bandhu",
    "site_header": "vaidya Bandhu",
    "welcome_sign": "Welcome to the Vaidya Bandhu",
    "show_ui_builder": True,
}


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "KALAKSHETRA.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "KALAKSHETRA.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': env('DBENGINE'),
    #     'NAME': env('DATABASE'),
    #     'USER': env('DBUSER'),
    #     'PASSWORD': env('DBPASSWORD'),
    #     'HOST': env('DBHOST'),
    #     'PORT': env('PORT'),
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'uni-test',
    #     'USER': 'postgres',
    #     'PASSWORD': 'postgres',
    #     'HOST': '3.106.236.167',
    #     'PORT': '5432',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'vaidya',
    #     'USER': 'postgres',
    #     'PASSWORD': 'Fogus_1234',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }

    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'vaidya',
        'USER': 'vaidya_postgres',
        'PASSWORD': 'Bandhu@Vaidya@2025',
        'HOST': '52.66.199.115',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True

USE_TZ = True

# Optional: Apply format to admin views even if localization is off
USE_L10N = False

# Optional: Customize time and date format (applies to templates using |date:"DATETIME_FORMAT")
DATETIME_FORMAT = 'd M Y, H:i:s'  # e.g., "10 May 2025, 14:30:00"
DATE_FORMAT = 'd M Y'  # e.g., "10 May 2025"
TIME_FORMAT = 'H:i:s'  # e.g., "14:30:00"

# -----------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
VALID_IMAGE_FILE_EXTENSIONS = ["jpg", "jpeg", "png", "gif", "webp"]
MAX_FILE_UPLOAD_SIZE = 10

AWS_ACCESS_KEY_ID = "AKIAZYHPEV6UQIZNMPEO"
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = "vaidya-bhandhu-prod"
AWS_S3_REGION_NAME = "ap-south-1"

# Use regional endpoint (safer than generic s3.amazonaws.com)
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

# Default storage backend → custom MediaStorage class
DEFAULT_FILE_STORAGE = "utils.custom_storages.MediaStorage"

# Media files will be stored under s3://bucket-name/media/
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
# Default primary key
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
# Security settings for production
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # Domain settings
    DOMAIN_NAME = env('DOMAIN_NAME')
    SITE_URL = env('SITE_URL')

    # Update CSRF settings for the domain
    if DOMAIN_NAME:
        CSRF_COOKIE_DOMAIN = DOMAIN_NAME
        # CSRF_TRUSTED_ORIGINS = [f"https://{DOMAIN_NAME}", f"https://www.{DOMAIN_NAME}"]

AUTH_USER_MODEL = 'user_details.User'

exceptions_mapping_file = open(os.path.join(BASE_DIR, 'utils/exceptions_mapping.json'), "r")
EXCEPTIONS_MAPPING = json.loads(exceptions_mapping_file.read())
exceptions_mapping_file.close()

AUTHENTICATION_BACKENDS = (
    # 'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesBackend',
    'utils.custom_authentication.CustomPatientAuthBackend',
)

JWT_AUTH = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=90),
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=90),
}

REST_FRAMEWORK = {
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "utils.custom_pagination.CustomPagination",
    "PAGE_SIZE": 15,
}

MAX_FILE_UPLOAD_SIZE = 10  # int(env('MAX_FILE_UPLOAD_SIZE_IN_MB', default=''))
SILENCED_SYSTEM_CHECKS = ["ckeditor.W001"]

AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = datetime.timedelta(minutes=1)
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_USERNAME_FORM_FIELD = 'mobile'

MAX_PAGINATION_SIZE = 10
HARDCODED_MOBILE_NO = +919880000300
HARDCODED_MOBILE_OTP = '1234'
IS_PRODUCTION = True
OTP_LENGTH = 4
OTP_CHARACTERS = '0123456789'
OTP_EXPIRATION_TIME = 300
SMS_USERNAME = "vaidyabandhu"
SMS_PASSWORD = "ihLS_04-"
SMS_SENDER = "VDYABN"
PAGE_SIZE = 15
RAZORPAY_KEY_ID = 'rzp_live_RBDq4cloXLAvYR'
RAZORPAY_KEY_SECRET = 'co1CQgBuAOTyyJsA7FHEUVLB'
BED_BASE_URL = 'localhost:8000'
VB_SUPPORT_NUMBER = '+91-8535853589'
