# Generated by Django 5.2 on 2025-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticcategory',
            name='hospital',
        ),
        migrations.AddField(
            model_name='diagnosticcategory',
            name='code',
            field=models.CharField(default=None, max_length=24),
            preserve_default=False,
        ),
    ]
