# Generated by Django 5.2 on 2025-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_remove_diagnosticcategory_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='code',
            field=models.CharField(default=None, max_length=24),
            preserve_default=False,
        ),
    ]
