# Generated by Django 5.2 on 2025-07-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_diagnostictest_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
