# Generated by Django 5.2 on 2025-07-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_diagnostictest_created_at_diagnostictest_updated_at_and_more'),
        ('hospital', '0005_department_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=8)),
                ('category', models.ManyToManyField(related_name='diagnostic_centers', to='diagnostic.diagnosticcategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
