# Generated by Django 5.2 on 2025-09-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_diagnosticcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticcenter',
            name='category',
            field=models.ManyToManyField(related_name='diagnostic_centers', to='diagnostic.diagnostictest'),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
