# Generated by Django 5.2 on 2025-09-18 20:23

import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0006_alter_diagnosticcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticcenter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticcenter',
            name='name',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='diagnosticcenter',
            name='pincode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
