# Generated by Django 5.2 on 2025-09-19 06:44

import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0007_alter_diagnosticcenter_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticcenter',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='diagnosticcenter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
