# Generated by Django 5.2 on 2025-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_languages'),
        ('user_details', '0008_remove_user_production_house_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_languages', to='master_data.languages'),
        ),
    ]
