# Generated by Django 5.2 on 2025-05-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_agegroup'),
        ('user_details', '0009_user_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_age_group', to='master_data.agegroup'),
        ),
    ]
