# Generated by Django 5.2 on 2025-06-07 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_skills'),
        ('user_details', '0014_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='master_data.subdepartment'),
        ),
    ]
