# Generated by Django 4.2.20 on 2025-05-19 07:38

import apps.web_pages.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.constants
import utils.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, help_text='Main content of the page', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('featured_image', models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.web_pages.models.generate_page_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity])),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', null=True)),
                ('is_homepage', models.BooleanField(default=False, help_text='Set as homepage')),
                ('show_in_menu', models.BooleanField(default=False, help_text='Show in navigation menu')),
                ('menu_order', models.PositiveIntegerField(default=0, help_text='Order in navigation menu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='web_pages.page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_structure', models.TextField(help_text='HTML structure for the template')),
                ('css_styles', models.TextField(blank=True, help_text='CSS styles for the template', null=True)),
                ('js_code', models.TextField(blank=True, help_text='JavaScript code for the template', null=True)),
            ],
            options={
                'verbose_name': 'Page Template',
                'verbose_name_plural': 'Page Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('gallery', 'Gallery'), ('video', 'Video'), ('html', 'HTML'), ('form', 'Form'), ('map', 'Map')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.web_pages.models.generate_page_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('css_class', models.CharField(blank=True, help_text='CSS class for styling', max_length=255, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Additional settings for the section')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web_pages.page')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='web_pages.pagetemplate'),
        ),
    ]
