# Generated by Django 5.2 on 2025-07-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ratings',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
