# Generated by Django 5.2 on 2025-07-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_gender'),
        ('hospital', '0005_department_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('code',)},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(to='hospital.hospital'),
        ),
    ]
