# Generated by Django 5.2 on 2025-07-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_email_doctor_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='full_name',
        ),
    ]
