# Generated by Django 5.2 on 2025-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_alter_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=755, null=True),
        ),
    ]
