# Generated by Django 5.2 on 2025-09-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_username_alter_doctor_password'),
        ('hospital', '0010_alter_hospital_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_department', to='hospital.department'),
        ),
    ]
