# Generated by Django 5.2 on 2025-05-03 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_rename_budget_movie_total_budget'),
        ('production_house', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('actors_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('director_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('crew_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('marketing_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('is_collaborated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='movies.movie')),
                ('production_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='production_house.productionhouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieBudgetResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('crew', 'Crew')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=False)),
                ('movie_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
