# Generated by Django 5.2 on 2025-05-30 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('movies', '0007_alter_movie_release_date'),
        ('production_house', '0006_productionhouse_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_movie', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='production_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_production_house', to='production_house.productionhouse'),
        ),
    ]
