# Generated by Django 5.2 on 2025-05-22 18:03

import apps.production_house.models
import django.core.validators
import utils.constants
import utils.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0002_productionhouse_cower_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhouse',
            name='awards',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='certificate',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storages.MediaStorage(), upload_to=apps.production_house.models.generate_ph_certificate_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), utils.constants.validate_file_size, utils.constants.validate_file_authenticity]),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='founder_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='mask_bank_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='office_address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='pan_card',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='registered_movies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='gst_number',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
