# Generated by Django 4.2.20 on 2025-05-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0002_productionhouse_cower_picture_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='productionhouse',
        #     old_name='cower_picture',
        #     new_name='cower_pictire',
        # ),
    ]
