# Generated by Django 5.2 on 2025-05-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0003_productionhouse_awards_productionhouse_certificate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionHouseOwnership',
        ),
    ]
