# Generated by Django 5.2 on 2025-05-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0003_rename_cower_picture_productionhouse_cower_pictire'),
        ('production_house', '0004_delete_productionhouseownership'),
    ]

    operations = [
    ]
